### ISSUE TITLE
Problem with self signed certificates

### ISSUE THREAD

**Issue by scphantm** [PacoVK/antora-confluence#52]
My confluence is internal.  We have a self signed certificate.  When i try to run the confluence exporter, i get this

```
error: undefined {"code":"SELF_SIGNED_CERT_IN_CHAIN","errno":"SELF_SIGNED_CERT_IN_CHAIN","type":"system"}
[18:47:40.740] FATAL (antora): Cannot read properties of undefined (reading 'results')
    Cause: TypeError
        at initializeState (/antora/node_modules/antora-confluence/dist/lib/service/StateService.js:25:18)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async publishToConfluence (/antora/node_modules/antora-confluence/dist/index.js:28:19)
        at async Promise.all (index 2)
        at async generateSite (/antora/node_modules/@antora/site-generator/lib/generate-site.js:53:12)
        at async Command.parseAsync (/antora/node_modules/commander/lib/command.js:936:5)
```

I checked the code and i don't see anything in it to disable ssl verification.  I don't know ruby enough to fix this myself

Is there another way to do this?  environment variable or something?

**Comment by slonopotamus** [comment]
Add your cert (or its CA) to trusted list?
